Add Mawranth's Hair stuff
I-am-Erk/CDDA-Tilesets pull request #2360
Opened 2024-04-30 15:12 UTC by Mawranth

#### Summary
Multiple hair styles & colour variations.

#### Content of the change

Changes to JSON data files and the individual PNGs of the hair styles.

#### Additional information
I've never done this before. Let me know if I did anything wrong.

2024-04-30 20:21 UTC, Mawranth commented on gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/mutations/hair/overlay_male_mutation_hair.json
> +	  "fg": [ "overlay_male_mutation_hair_beaded_var_black" ],
Okay. I removed the files. I do not have a PR to the main game repo,

2024-05-02 11:36 UTC, Fris0uman commented on gfx/MShockXotto+/pngs_tiles_32x32/character/overlay/mutations/hair/overlay_female_mutation_hair.json
> -    "fg": [ "overlay_female_mutation_hair_black_crewcut" ],
this part should not have been removed, as you can see the id and fg field there are not the same.

2024-05-02 11:37 UTC, Fris0uman commented
I'll merge the sprites into the tileset if/when the hair styles are actually added to the game

2024-05-02 17:03 UTC, Mawranth commented
> I'll merge the sprites into the tileset if/when the hair styles are actually added to the game

That's fine. It's not like this is going anywhere.

2024-05-03 00:02 UTC, BalthazarArgall commented
> I'll merge the sprites into the tileset if/when the hair styles are actually added to the game

Not merged yet but the PR adding them to the game can be found [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/73465) if you want to check that everything is set up correctly.

2024-05-11 18:20 UTC, LyleSY requested changes
The 1,240 lines of removed JSON need to be restored before this is merged. Otherwise I believe this is ready since the matching PR has been merged in DDA

2024-05-13 14:13 UTC, Fris0uman commented
Merged in #2372

2024-05-13 14:13 UTC, closed without merging