[Ultica] Sprites for boxes
I-am-Erk/CDDA-Tilesets pull request #2527
Opened 2024-09-18 12:19 UTC by GuakeTheAcinid

#### Summary

Added sprites for different types of boxes

#### Content of the change
item sprites:
- tiny wooden box
- small wooden box
- small plastic box
- compact wooden box
- medium wooden box
- large woodern box
- oversize wooden box
- military black box

human_body wielded overlay sprites:
- medium wooden box
- medium metal box
- small wooden box
- small metal box
- small plastic box
- military black box

#### Testing
![testToShowEverythingIsAlright](https://github.com/user-attachments/assets/4ba3cfd2-2aa2-49ec-ae25-7181e7240713)

#### Additional information

2024-09-20 21:19 UTC, Fris0uman requested changes
A few fix needed:
- Remove the unecessary json
- don't put your name on folders, name them something sensible like here `overlay_wielded_balc_box`  and `black_box` for exemple

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/wielded/by_Guake/overlay_wielded_black_box.json
> +    "id": [ "overlay_wielded_black_box" ],
unless `overlay_wielded_black_box` is also used in json somewhere else this is unecessary. Naming the file with the correct id is enough if you want that sprite to be used just for this id

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/wielded/containers/overlay_wielded_box.json
> +    },
```suggestion
```
You don't this

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_human_body_32x36/overlay/wielded/containers/overlay_wielded_box.json
> +    }
```suggestion
```
same

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_normal_32x32/items/containers/box_wood.json
> +    {
unnecessary

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_small_20x20/items/containers/box_small_plastic.json
> +{
don't need it

2024-09-20 21:19 UTC, Fris0uman commented on gfx/UltimateCataclysm/pngs_small_20x20/items/containers/box_wood.json
> +      "id": [ "box_small_wood" ],
don't need it

2024-09-25 08:05 UTC, GuakeTheAcinid commented
@Fris0uman, fixes are made.

2024-09-25 12:35 UTC, Fris0uman approved these changes

2024-09-25 12:35 UTC, merged